apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tt-tournoi.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tt-tournoi.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
data:
  ACCESS_TOKEN_EXPIRE_MINUTES: {{ .Values.backend.env.ACCESS_TOKEN_EXPIRE_MINUTES | quote }}
  ALGORITHM: "HS256"
