apiVersion: v1
kind: Service
metadata:
  name: {{ include "tt-tournoi.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tt-tournoi.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    {{- include "tt-tournoi.backend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
