apiVersion: v1
kind: Service
metadata:
  name: {{ include "tt-tournoi.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tt-tournoi.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    {{- include "tt-tournoi.frontend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
